### ISSUE TITLE
Error after adding ipv6

### ISSUE THREAD

**Issue by soncms** [DNSCrypt/encrypted-dns-server#118]
i add ipv6 to listen_addrs and can't start encrypted-dns

![image](https://user-images.githubusercontent.com/87874954/187132906-16fd0797-99e1-4910-b616-7668bdaf183a.png)

I tried running encrypted-dns with docker the ipv6 works fine but the query is very slow, is there any way to fix it

![image](https://user-images.githubusercontent.com/87874954/187133116-5bb02794-7f36-433e-bb45-b5d413dda740.png)

**Comment by jedisct1** [comment]
What error message do you get when starting the server directly from the command line (not without system d) ?
