### ISSUE TITLE
0.9.14 missing pre-built artifacts

### ISSUE THREAD

**Issue by xrisk** [DNSCrypt/encrypted-dns-server#232]
Might be some problem with the GH action

<img width="1217" alt="Screenshot 2024-03-17 at 10 07 33 PM" src="https://github.com/DNSCrypt/encrypted-dns-server/assets/10669859/16799761-e4a5-44d6-bc76-91f5a46d7267">

**Comment by jedisct1** [comment]
Maybe updating action-gh-release@v2 would fix it.

I'm going to try to tag a new version and see how it works.

**Comment by jedisct1** [comment]
Looks like it worked!
