### ISSUE TITLE
TLS Proxy: relaying the real client ip

### ISSUE THREAD

**Issue by blob42** [DNSCrypt/encrypted-dns-server#296]
Hi,

I am running a DoH and relaying https connections to my reverse proxy. All relayed tls traffic has the remote_ip set to the DoH server so implementing any kind of rate/spam control is difficult. 

Is there any way I could pass along the real remote client ip when it is proxied  ?
Or maybe add an extra header field ?

**Comment by jedisct1** [comment]
Relaying happens at layer 4. The proxy never decrypts the relayed TLS traffic and is not even able to.

But rate limiting is something that can be implemented in the proxy itself. I'm using firewall rules to limit the number of sessions per client IP, but doing it in user land could be easier to configure.

**Comment by blob42** [comment]
Thanks for the quick reply.

> Relaying happens at layer 4

Granted, how would I go about changing the source address of the relayed tls traffic ? As I understand the upstream server is using the source address to set the http remote ip. Would SNAT work without disturbing the TLS stream ? 

For info I am running DoH inside a docker container. All http traffic has as remote ip the DoH sever ip address.

**Comment by jedisct1** [comment]
That would not work without breaking the TCP stream.

**Comment by blob42** [comment]
Got it thanks again for the tips.

**Comment by blob42** [comment]
@jedisct1 I found a solution and updated the comment for future people who encounter the same problem
