### ISSUE TITLE
setting up access via meta tokens

### ISSUE THREAD

**Issue by pysiak** [DNSCrypt/encrypted-dns-server#50]
I setup encrypted-dns and now I'm trying to do access control using query_meta. It doesn't seem to work, am I doing it right?
encrypted-dns.toml has:
`tokens = ["abc123"]`
remote dnscrypt-proxy.toml has:
`query_meta = ["token:abc123"]`

This yields me SERVFAIL:
```
$ host -v cnn.com
Trying "cnn.com"
Host cnn.com not found: 2(SERVFAIL)
Received 25 bytes from X.X.X.X#53 in 65 ms
```

**Comment by pysiak** [comment]
bump? a dnscrypt-proxy to encrypted-dns-server setup works, until I setup the toknes as above, then it fails.
Wondering if there are any other users of doing access this way?

**Comment by jedisct1** [comment]
Unfortunately, I wasn't able to reproduce this :( It works :(

In `encrypted-dns.toml` I have

```toml
enabled = true
tokens = ["Y2oHkDJNHz", "G5zY3J5cHQtY", "C5zZWN1cmUuZG5z", "MySecretToken"]
```

And in `dnscrypt-proxy.toml`:

```toml
query_meta = ["key1:value1", "key2:value2", "token:MySecretToken"]
```

So I don't know what to look at :(

**Comment by pysiak** [comment]
Thanks, I'll investigate further then
