### ISSUE TITLE
Share the grafana dashboard

### ISSUE THREAD

**Issue by mmack** [DNSCrypt/encrypted-dns-server#66]
Hey @jedisct1,
it would be nice to checking the source or the grafana dashboard here. Would you mind?

Max

**Comment by jedisct1** [comment]
I'm not very familiar with Grafana. Is this what you need?

[dnscrypt.json](https://github.com/jedisct1/encrypted-dns-server/files/6718139/dnscrypt.txt)

**Comment by dapphp** [comment]
Thank JSON template worked great, thanks Frank!
