### ISSUE TITLE
No useable certificate found

### ISSUE THREAD

**Issue by rgzn-aiyun** [DNSCrypt/encrypted-dns-server#69]
This error occurred after 24 hours of back-office operation and appears to have been caused by the failure to update the certificate?

**Comment by jedisct1** [comment]
Check that your clocks are properly set, maybe? Certificates are only valid for up 24 hours, but are rotated every 8 hours.

**Comment by rgzn-aiyun** [comment]
Time's good. It's the program that's running from backstage that's wrong.

**Comment by jedisct1** [comment]
Maybe try https://github.com/DNSCrypt/dnscrypt-server-docker ? It comes with everything already configured.

**Comment by rgzn-aiyun** [comment]
Or is there a problem with the daemon?

**Comment by jedisct1** [comment]
Works for me and for all the public servers.

Unfortunately, a more verbose bug report may be necessary in order to understand and reproduce what you are trying to describe.
