### ISSUE TITLE
Mem leak?

### ISSUE THREAD

**Issue by dct-infra** [DNSCrypt/encrypted-dns-server#70]
Hello,
I've upgraded from 0.3.23 to 0.9.1 on a mostly idling virtual server running debian 11 with a custom kernel, 2x Intel cpu vcores and 1GB RAM.

The server used to be stable and running smoothly until the upgrade.
Mem usage went from around 19% to around 52% and up for no obvious reasons.

Some porbably not really useful syslog entries can be found below :
<...> oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),task=encrypted-dns,pid=1719
<...> **Out of memory**: Killed process 1719 (encrypted-dns) total-vm:1212052kB, anon-rss:573912kB, file-rss:0kB, shmem-rss:0kB, UID: pgtables:1520kB oom_score_adj:0

On the other hand, the upgrade had no impact on another virtual server running with only 512MB RAM and 1 vcore ( same OS, kernel and dns/encrypted-dns config as the other).

Have you already had similar issues reported?
Any ideas why this might be happening?

I've downgraded to 0.3.23, thigs are back to normal and currently monitoring.

Thanks.

**Comment by jedisct1** [comment]
Unfortunately, no. I haven't noticed anything similar and I don't know what could be doing this :(

The main differences between 0.3.23 and 0.9.1 are dependency updates, so you can keep using 0.3.23.

Besides dependency updates, a possible culprit might be dbed0a086720ad276f2c0276a0f1f0dc13c3c397 

Ca you try reverting that change and see if it makes a difference?
