### ISSUE TITLE
Updated glibc dependency for 0.9.1

### ISSUE THREAD

**Issue by dapphp** [DNSCrypt/encrypted-dns-server#71]
The Debian package for 0.9.1 requires libc6 >= 2.31 where previously it required >= 2.27.

I'm running the stable "buster" release of Debian (10.10) which currently supplies packages for glibc 2.28, so upgrading to 0.9.1 using the provided Debian package is not possible on the current stable platform. I know there aren't RPM's but even CentOS 8 is only at 2.28 so it seems like the requirement for glibc >= 2.31 might be a little high when running on stable systems.

Any chance of lowering the glibc requirement back down to 2.27 or 2.28 so the deb will install on the stable buster release?

Thanks!

**Comment by jedisct1** [comment]
The new Debian release probably has a newer libc :)
