### ISSUE TITLE
Latest pre-built binary has .bz2 extension but uses XZ

### ISSUE THREAD

**Issue by herver** [DNSCrypt/encrypted-dns-server#74]
Hello !

I wanted to update a test node to the latest release and noticed that I couldn't extract the pre-built binary, because of:

```
$ tar jxvf encrypted-dns_0.9.1_linux-x86_64.tar.bz2
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

$ file encrypted-dns_0.9.1_linux-x86_64.tar.bz2
encrypted-dns_0.9.1_linux-x86_64.tar.bz2: XZ compressed data, checksum CRC64
```

Would it be possible to either, switch to `.xz` extension, or make sure it is using `bzip2` ? :smile: 

Thank you for your great projects !

**Comment by jedisct1** [comment]
Oh, good catch thanks!

The wrong option was used in the `tar` command line.

Will be fixed in the next release!

Thanks again!
