### ISSUE TITLE
No useable certificate found (part 2)

### ISSUE THREAD

**Issue by ztheory** [DNSCrypt/encrypted-dns-server#76]
I'm seeing the same issue as mentioned in #69.

24 hours after starting encrypted-dns-server with `daemonize=true`, starting dnscrypt-proxy on the client with the relay set results in ```No useable certificate found```.

Checked clocks are in sync using ntpd. Tried both UTC and local timezone.

Issue occurs on two VPS servers with different providers, both running 64-bit Debian 11 using the precompiled .deb package.

**Comment by jedisct1** [comment]
Damn. Can you try without `-daemonize`?

**Comment by ztheory** [comment]
When `daemonize=false` is set, I can't replicate the issue so far. Will test for another 48 hours with both relays to make sure.

**Comment by ztheory** [comment]
Can confirm that when when `daemonize=false` is set, no recurrence after ~5 days.
