### ISSUE TITLE
Memory problem ?

### ISSUE THREAD

**Issue by Haraade** [DNSCrypt/encrypted-dns-server#86]
I have had memory problems in dnscrypt server-docker images. 
Memory usage is growing rapidly.
Come across this: 
https://github.com/tikv/rust-prometheus/issues/424 
Could prometheus v0.13.0 be the problem?
Compiled encrypted-dns with prometheus v0.12.0 and it looks like memory problem is gone.
This was done on a singleboard computer arm32v7 with 2Gbyte of LPDDR3 RAM.

**Comment by Haraade** [comment]
Do not know what does this, tried on another arm32v7 board. CPU (1-core of 4) usage also goes up to 100%

![dnscrypt-server](https://user-images.githubusercontent.com/23292068/169666360-a2904ee2-08d0-46c8-810f-1b400208601c.jpg)

**Comment by jedisct1** [comment]
Can you double check that the issue goes away when downgrading the prometheus crate to v0.12.0?

How did you do that?

**Comment by Haraade** [comment]
The weird thing is that one device works with prometheus v0.12.0 and another does not (release 0.9.1), but both devices work well with encrypted-dns release 0.3.23 and arm32v7/ubuntu:22.04

Build dnscrypt-server-docker, FROM arm32v7/ubuntu:22.04

**Comment by Haraade** [comment]
I have also tried prometheus v0.13.1, but there are also issues.
https://github.com/tikv/rust-prometheus/issues/442

**Comment by jedisct1** [comment]
Does it still happen if you don't enable the `metrics` feature? (disabling it removes prometheus)

**Comment by Haraade** [comment]
> Does it still happen if you don't enable the `metrics` feature? (disabling it removes prometheus)

I have to try.

**Comment by Haraade** [comment]
disabled metrics in encrypted-dns.toml.in and -M option when initializing the docker image.
Memory and CPU usage are growing, and are running in loop.

![dnscrypt-server](https://user-images.githubusercontent.com/23292068/169690339-2d804ec0-57c7-4589-b9f3-2f4046ba96f6.jpg)
![dnscrypt-server](https://user-images.githubusercontent.com/23292068/169690342-629200c2-a972-4c60-96d1-c55b3a061279.jpg)

**Comment by jedisct1** [comment]
Ok, so at least we know that this is unrelated to Prometheus.

In case this is not in a dependency, would you be able to pinpoint a specific commit that introduced this?

**Comment by Haraade** [comment]
Version 0.3.23 works.
cargo install --git https://github.com/DNSCrypt/encrypted-dns-server --rev 631ebd4776b3d697014867b535988ae4e6d33fe0

Version 0.9.0 does not work.
cargo install --git https://github.com/DNSCrypt/encrypted-dns-server --rev a178d252f5078d1463f6aa03684d066d0e5e0fe9 

So there must be something between these versions.

Will probably have to test more to find the specific commit that introduced this.

**Comment by Haraade** [comment]
I think this problem is due to jemallocator.

See what was mentioned earlier.
https://github.com/jemalloc/jemalloc/issues/1497
https://github.com/gnzlbg/jemallocator/issues/168
https://github.com/rust-lang/rust/pull/83152

I have tried with tikv-jemallocator. Compiled fine and without memory problem, but unfortunately no response from encrypted-dns. Only gets TIMEOUT on server in dnscrypt proxy. 
tikv-jemallocator supports arm32v7 ?

**Comment by jedisct1** [comment]
So, like way too many Rust crates, jemalloc is abandoned, and the maintained fork doesn't work on ARM? Great :(

As an experiment, 748b944a611046eb0c013bdf946ce5b40888ba8e replaces `jemalloc` with `mimalloc`. Does in improve things on your end?

**Comment by jedisct1** [comment]
The app doesn't seem to compile at all on armv7 :(

```text
error[E0308]: mismatched types
   --> /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/prometheus-0.13.1/src/process_collector.rs:192:13
    |
190 |     static ref CLK_TCK: i64 = {
    |                         --- expected `i64` because of return type
191 |         unsafe {
192 |             libc::sysconf(libc::_SC_CLK_TCK)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `i32`
```

**Comment by jedisct1** [comment]
After removing prometheus' `process` feature, it works for me on armv7l (raspberry Pi with 32-bit raspbian).

**Comment by Haraade** [comment]
Update.
Has compiled with the latest version of tikv-jemallocator (0.5.0), which was released today and server works excellent. 
https://github.com/tikv/jemallocator/pull/26
This issue has been resolved. Thank you so much
