### ISSUE TITLE
Add Cargo.lock to repository (remove from gitignore)

### ISSUE THREAD

**Issue by joachimschmidt557** [DNSCrypt/encrypted-dns-server#90]
According to [the Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html), executables should include the `Cargo.lock` file in their git repositories to enable reproducible builds and make packaging easier.

**Comment by jedisct1** [comment]
In practice, this is unfortunately a massive pain when PRs (or anything to be merged) are not based on the very latest `Cargo.toml` version, with an up to date `Cargo.lock` generated a compatible Rust version.

As a contributor to some Rust projects, I really hate that every time.

But well... given that there isn't a lot of external contributions to that project, it may be fine...

**Comment by jedisct1** [comment]
Reproducible builds is not something Rust supports yet: https://github.com/rust-lang/rust/labels/A-reproducibility

**Comment by joachimschmidt557** [comment]
Thanks! I should add: the reason for this "proposal" was that I'm trying to package this project for Nixpkgs, which [requires the presence of a `Cargo.lock` file](https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo) to make it "reproducible" enough for Nixpkgs.

If the `Cargo.lock` file is too much of a burden in the future, it can be patched in by the Nixpkgs build script.
