### ISSUE TITLE
Mem issue

### ISSUE THREAD

**Issue by dct-infra** [DNSCrypt/encrypted-dns-server#93]
Hello Franck,
I have tried an upgrade from 0.3.23 to 0.9.6 using the deb package but I'm having a hard time dealing with a mem related issue.
On start, the daemon gets killed right a way by oom-killer with the folowing output :
Out of memory: Killed process 12208 (encrypted-dns) total-vm:3947028kB, anon-rss:3103292kB, file-rss:180kB, shmem-rss:0kB, UID:1000 pgtables:7056kB oom_score_adj:0

Noting that the machine has enough RAM but no swap (on purpose)
Moreover, on start the folowing WARN appears :
[WARN  encrypted_dns] Unable to set the number of open files to 5024. The hard limit is 4096
[INFO  encrypted_dns] Dropping privileges

No hard limits whatsoever are set for the superuser.
I have tried to find the reasons that might cause this on the system level, no clue.
Thank you in advance for any advices.

**Comment by jedisct1** [comment]
Oh, I just noticed that 0.9.7 was tagged in git, but for some reason, GitHub still lists 0.9.6 as the latest release.

Thanks for spotlighting this. Looking...

**Comment by jedisct1** [comment]
Errr... indeed, a manual action was needed to get GitHub update the release in the release page.

So... Try 0.9.7!

**Comment by dct-infra** [comment]
Same behavior with 0.9.7, I had to go back to 0.3.23
