### ISSUE TITLE
Is there a Windows or Docker version?

### ISSUE THREAD

**Issue by Cortana-117** [DNSCrypt/encrypted-dns-server#95]
it has good graphical UI but I don't want to run a VM an an entire Linux OS just for this.

I already use DNScrypt-proxy on Windows 11 and it works great, but the extra user interface with those info got me curious to try this one too, but a bummer that it doesn't work on Windows.

**Comment by jedisct1** [comment]
It works on Windows, thanks to @lifenjoiner 's work.

However, you have to compile it yourself, there are no pre-built packages.

**Comment by lifenjoiner** [comment]
There will be official pre-built packages for Windows in future releases.
If you can't wait, you can have a try with [this temporary one](https://github.com/lifenjoiner/encrypted-dns-server/releases/tag/TestRelease).
Good luck!
